services:
  - type: web
    name: hotel_booking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hotel_booking.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0  # or your preferred Python version
      - key: DEBUG
        value: False