# Generated by Django 5.0.6 on 2024-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_image_hotel_video_room_image_room_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('hotel_admin', 'Hotel Admin'), ('system_admin', 'System Admin')], default='client', max_length=20),
        ),
    ]
