# Generated by Django 5.0.6 on 2024-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
