# Generated by Django 5.0.6 on 2024-07-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_is_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotel.hotel'),
        ),
    ]
