# Generated by Django 5.0.6 on 2024-07-27 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
